version: "3.7"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./other/nginx/local/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/var/keys/letsencrypt
      - ./keys/self-signed:/var/keys/self-signed/
      - ./public:/var/www/tri-base/public
    networks:
      tri-base-net:
         ipv4_address: 10.5.0.2   

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_USER=tri_base
      - MYSQL_PASSWORD=tri_base
      - MYSQL_DATABASE=tri_base
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    networks:
      tri-base-net:
         ipv4_address: 10.5.0.3

  tribase:
    image: tribase
    container_name: tribase
    build: ./server
    environment:
      - TRI_BASE_CONFIG_NAME=local1
    working_dir: /var/www/tri-base/server
    volumes:
      - ./:/var/www/tri-base
    command: node run.js
    networks:
      tri-base-net:
        ipv4_address: 10.5.0.5
        aliases:
          - tribase
          - m3
    depends_on:
      - mysql
      - nginx

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql-volume:

networks:
  tri-base-net:
    driver: bridge
    ipam:
       config:
          - subnet: 10.5.0.0/16
            gateway: 10.5.0.1
